---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoë.
--- DateTime: 11/04/2022 18:32
---

local events = {};

function events:CHAT_MSG_GUILD(...)
    local args = {...}
    KeysBM.utils.reply(args, "GUILD")
end

function events:CHAT_MSG_PARTY(...)
    local args = {...}
    KeysBM.utils.reply(args, "PARTY")
end

function events:CHAT_MSG_RAID(...)
    local args = {...}
    KeysBM.utils.reply(args, "RAID")
end

function events:CHAT_MSG_SAY(...)
    local args = {...}
    KeysBM.utils.reply(args, "SAY")
end

KeysBM.frame:SetScript(
        "OnEvent",
        function(self, event, ...)
            events[event](self, ...); -- call one of the functions above
        end
)

for k, v in pairs(events) do
    KeysBM.frame:RegisterEvent(k); -- Register all events for which handlers have been defined
end

KeysBM.events = events;