---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoë.
--- DateTime: 11/04/2022 18:32
---

local utils = {};

function utils.reply(args, channel)
    if args[1]:lower() == "!keys" then
        SendChatMessage(KeysBM.msgs[math.random(1, (#KeysBM.msgs)+1)], channel)
    end
end

KeysBM.utils = utils